In [1]:
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

In [4]:
np.random.rand(5,5)

array([[ 0.01045001,  0.01097451,  0.9525411 ,  0.1077146 ,  0.96469161],
       [ 0.47994708,  0.15145462,  0.35663256,  0.09980872,  0.65265603],
       [ 0.2836476 ,  0.82162221,  0.19248972,  0.54374883,  0.26988305],
       [ 0.11637903,  0.16373435,  0.59298357,  0.91993276,  0.90570412],
       [ 0.0426613 ,  0.49639025,  0.2593164 ,  0.68452774,  0.66136741]])

In [5]:
pd.date_range("20130101",periods=6)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [21]:
df=pd.DataFrame({"A":1,"B":np.random.rand(5),"C":pd.Series(np.arange(5),dtype=np.float32),"D":np.array([3]*5),"F":'foo'})
df

A         B    C  D    F
0  1  0.037926  0.0  3  foo
1  1  0.021592  1.0  3  foo
2  1  0.698775  2.0  3  foo
3  1  0.651240  3.0  3  foo
4  1  0.525734  4.0  3  foo

In [22]:
print df.dtypes

A      int64
B    float64
C    float32
D      int32
F     object
dtype: object


In [28]:
df.index,df.columns,df.values

(RangeIndex(start=0, stop=5, step=1),
 Index([u'A', u'B', u'C', u'D', u'F'], dtype='object'),
 array([[1L, 0.0379262003777695, 0.0, 3, 'foo'],
        [1L, 0.021591772471566184, 1.0, 3, 'foo'],
        [1L, 0.6987745318253916, 2.0, 3, 'foo'],
        [1L, 0.6512398458154921, 3.0, 3, 'foo'],
        [1L, 0.5257337734287482, 4.0, 3, 'foo']], dtype=object))

In [29]:
df.describe()

A         B         C    D
count  5.0  5.000000  5.000000  5.0
mean   1.0  0.387053  2.000000  3.0
std    0.0  0.332283  1.581139  0.0
min    1.0  0.021592  0.000000  3.0
25%    1.0  0.037926  1.000000  3.0
50%    1.0  0.525734  2.000000  3.0
75%    1.0  0.651240  3.000000  3.0
max    1.0  0.698775  4.000000  3.0

In [30]:
df.T

0          1         2        3         4
A          1          1         1        1         1
B  0.0379262  0.0215918  0.698775  0.65124  0.525734
C          0          1         2        3         4
D          3          3         3        3         3
F        foo        foo       foo      foo       foo

In [31]:
df.sort_index(ascending=False)

A         B    C  D    F
4  1  0.525734  4.0  3  foo
3  1  0.651240  3.0  3  foo
2  1  0.698775  2.0  3  foo
1  1  0.021592  1.0  3  foo
0  1  0.037926  0.0  3  foo

In [32]:
df

A         B    C  D    F
0  1  0.037926  0.0  3  foo
1  1  0.021592  1.0  3  foo
2  1  0.698775  2.0  3  foo
3  1  0.651240  3.0  3  foo
4  1  0.525734  4.0  3  foo

In [34]:
df.sort_index(ascending=False,inplace=True)
df

A         B    C  D    F
4  1  0.525734  4.0  3  foo
3  1  0.651240  3.0  3  foo
2  1  0.698775  2.0  3  foo
1  1  0.021592  1.0  3  foo
0  1  0.037926  0.0  3  foo

In [35]:
df.sort_values("B")

A         B    C  D    F
1  1  0.021592  1.0  3  foo
0  1  0.037926  0.0  3  foo
4  1  0.525734  4.0  3  foo
3  1  0.651240  3.0  3  foo
2  1  0.698775  2.0  3  foo

In [37]:
df.loc[1]

A            1
B    0.0215918
C            1
D            3
F          foo
Name: 1, dtype: object

In [43]:
df[1:2]

A        B    C  D    F
3  1  0.65124  3.0  3  foo

In [44]:
df[1]

KeyError: 1

In [45]:
df

A         B    C  D    F
4  1  0.525734  4.0  3  foo
3  1  0.651240  3.0  3  foo
2  1  0.698775  2.0  3  foo
1  1  0.021592  1.0  3  foo
0  1  0.037926  0.0  3  foo

In [46]:
df.loc[:,["A","B"]]

A         B
4  1  0.525734
3  1  0.651240
2  1  0.698775
1  1  0.021592
0  1  0.037926

In [52]:
df=df.reindex(np.arange(5))
df

A         B    C  D    F
0  1  0.037926  0.0  3  foo
1  1  0.021592  1.0  3  foo
2  1  0.698775  2.0  3  foo
3  1  0.651240  3.0  3  foo
4  1  0.525734  4.0  3  foo

In [53]:
df.loc[1:3,["A","B"]]

A         B
1  1  0.021592
2  1  0.698775
3  1  0.651240

In [58]:
df.loc[[1,3],["A","B"]]

A         B
1  1  0.021592
3  1  0.651240

In [54]:
df.iloc[1,3]

3

In [56]:
df.iloc[0:2,0:2]

A         B
0  1  0.037926
1  1  0.021592

In [60]:
df[df.C>0.5]

A         B    C  D    F
1  1  0.021592  1.0  3  foo
2  1  0.698775  2.0  3  foo
3  1  0.651240  3.0  3  foo
4  1  0.525734  4.0  3  foo

In [64]:
df2=df
df2['E']= ['one','two','three','four','three']
print df2
print df

   A         B    C  D    F      E
0  1  0.037926  0.0  3  foo    one
1  1  0.021592  1.0  3  foo    two
2  1  0.698775  2.0  3  foo  three
3  1  0.651240  3.0  3  foo   four
4  1  0.525734  4.0  3  foo  three
   A         B    C  D    F      E
0  1  0.037926  0.0  3  foo    one
1  1  0.021592  1.0  3  foo    two
2  1  0.698775  2.0  3  foo  three
3  1  0.651240  3.0  3  foo   four
4  1  0.525734  4.0  3  foo  three


In [104]:
df3=df.copy()
df3['G']= ['one','two','three','four','three']
print df3
print df

   A         B    C  D    F      E      G
0  1  0.000000  0.0  3  foo    one    one
1  0  0.021592  1.0  3  foo    two    two
2  1  0.698775  2.0  3  foo  three  three
3  1  0.651240  3.0  3  foo   four   four
4  1  0.525734  4.0  3  foo  three  three
   A         B    C  D    F      E
0  1  0.000000  0.0  3  foo    one
1  0  0.021592  1.0  3  foo    two
2  1  0.698775  2.0  3  foo  three
3  1  0.651240  3.0  3  foo   four
4  1  0.525734  4.0  3  foo  three


In [72]:
print df2['E'].isin(['two',"furo"])
df2[df2['E'].isin(['two',"furo"])]

0    False
1     True
2    False
3    False
4    False
Name: E, dtype: bool


A         B    C  D    F    E
1  1  0.021592  1.0  3  foo  two

In [73]:
df

A         B    C  D    F      E
0  1  0.037926  0.0  3  foo    one
1  1  0.021592  1.0  3  foo    two
2  1  0.698775  2.0  3  foo  three
3  1  0.651240  3.0  3  foo   four
4  1  0.525734  4.0  3  foo  three

In [83]:
df.loc[1,"A"]=0
df.iloc[0,1]=0
df

A         B    C  D    F      E
0  1  0.000000  0.0  3  foo    one
1  0  0.021592  1.0  3  foo    two
2  1  0.698775  2.0  3  foo  three
3  1  0.651240  3.0  3  foo   four
4  1  0.525734  4.0  3  foo  three

In [105]:
df3=df3.iloc[:,:4]
df3

A         B    C  D
0  1  0.000000  0.0  3
1  0  0.021592  1.0  3
2  1  0.698775  2.0  3
3  1  0.651240  3.0  3
4  1  0.525734  4.0  3

In [106]:
df3>1

A      B      C     D
0  False  False  False  True
1  False  False  False  True
2  False  False   True  True
3  False  False   True  True
4  False  False   True  True

In [107]:
df3[df3>1]

A   B    C  D
0 NaN NaN  NaN  3
1 NaN NaN  NaN  3
2 NaN NaN  2.0  3
3 NaN NaN  3.0  3
4 NaN NaN  4.0  3

In [108]:
df3[df3>1]=-df3
df3

A         B    C  D
0  1  0.000000  0.0 -3
1  0  0.021592  1.0 -3
2  1  0.698775 -2.0 -3
3  1  0.651240 -3.0 -3
4  1  0.525734 -4.0 -3

In [111]:
df.iloc[1,1]=np.nan
df

A         B    C  D    F      E
0  1  0.000000  0.0  3  foo    one
1  0       NaN  1.0  3  foo    two
2  1  0.698775  2.0  3  foo  three
3  1  0.651240  3.0  3  foo   four
4  1  0.525734  4.0  3  foo  three

In [113]:
df.dropna(how='any')

A         B    C  D    F      E
0  1  0.000000  0.0  3  foo    one
2  1  0.698775  2.0  3  foo  three
3  1  0.651240  3.0  3  foo   four
4  1  0.525734  4.0  3  foo  three

In [123]:
df["E"].value_counts()

three    2
one      1
two      1
four     1
Name: E, dtype: int64

In [133]:
print df.E,'\n',type(df.E)

['one', 'one', 'two', 'three', 'four', 'three'] 
<type 'list'>


In [132]:
print df["E"],'\n',type(df["E"])

0      one
1      two
2    three
3     four
4    three
Name: E, dtype: object 
<class 'pandas.core.series.Series'>


In [134]:
print df["E"].values,'\n',type(df["E"].values)

['one' 'two' 'three' 'four' 'three'] 
<type 'numpy.ndarray'>


In [143]:
import re
filter(lambda x:re.search('.*low.*',x),dir(df["F"]))

['_allow_index_ops', 'clip_lower']

In [144]:
filter(lambda x:re.search('.*low.*',x),dir(df.F))

['_allow_index_ops', 'clip_lower']

In [148]:
filter(lambda x:re.search('.*low.*',x),dir(df["F"].values))

[]

In [151]:
filter(lambda x:re.search('.*low.*',x),dir(df["F"].str))

['islower', 'lower']

In [169]:
left = pd.DataFrame({'key': ['foo', 'foo'], 'lval': [1, 2]})
right = pd.DataFrame({'key': ['foo', 'foo'], 'lval': [4, 5]})
print right,'\n',left
print "---------------------------------"
print pd.concat(objs=[left,right],axis=1)
print "---------------------------------"
print pd.concat(objs=[left,right],axis=0)

   key  lval
0  foo     4
1  foo     5 
   key  lval
0  foo     1
1  foo     2
---------------------------------
   key  lval  key  lval
0  foo     1  foo     4
1  foo     2  foo     5
---------------------------------
   key  lval
0  foo     1
1  foo     2
0  foo     4
1  foo     5


In [164]:
pd.merge(left,right,on="key")

key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5

In [170]:
df

A         B    C  D    F      E
0  1  0.000000  0.0  3  foo    one
1  0       NaN  1.0  3  foo    two
2  1  0.698775  2.0  3  foo  three
3  1  0.651240  3.0  3  foo   four
4  1  0.525734  4.0  3  foo  three

In [189]:
df.append(pd.Series([1,2,3,4,'bar','foru'],index=[u'A', u'B', u'C', u'D', u'F', u'E']),ignore_index=True)

A         B    C  D    F      E
0  1  0.000000  0.0  3  foo    one
1  0       NaN  1.0  3  foo    two
2  1  0.698775  2.0  3  foo  three
3  1  0.651240  3.0  3  foo   four
4  1  0.525734  4.0  3  foo  three
5  1  2.000000  3.0  4  bar   foru

In [191]:
df.groupby(["A"])["C","D"].sum()

C   D
A         
0  1.0   3
1  9.0  12

In [197]:
pd.pivot_table(df,index="A",values=["C","D"],aggfunc=np.sum)

C   D
A         
0  1.0   3
1  9.0  12

In [200]:
df["E"]

0      one
1      two
2    three
3     four
4    three
Name: E, dtype: object

In [203]:
df["E"]=df["E"].astype("category")
df["E"]

0      one
1      two
2    three
3     four
4    three
Name: E, dtype: category
Categories (4, object): [four, one, three, two]

In [204]:
df["E"]=df["E"].astype("category")
df["E"].cat.categories=[1,2,3,4]
df["E"]

0    2
1    4
2    3
3    1
4    3
Name: E, dtype: category
Categories (4, int64): [1, 2, 3, 4]

In [209]:
df3 = pd.DataFrame(np.random.randn(5, 3), index=['a', 'c', 'e', 'f', 'h'],
                     columns=['one', 'two', 'three'])
df3['four'] = 'bar'
df3

one       two     three four
a -0.446368 -0.203396 -0.325042  bar
c  1.347684 -0.104033  0.319408  bar
e  0.234271 -0.811917  2.012418  bar
f -0.669014  0.835397 -0.187838  bar
h  1.403727  1.168214 -0.175217  bar

In [221]:
print df3.isnull()
print "-----------------------------"
print df3.isnull()==False

     one    two  three   four
a  False  False  False  False
c  False  False  False  False
e  False  False  False  False
f  False  False  False  False
h  False  False  False  False
-----------------------------
    one   two three  four
a  True  True  True  True
c  True  True  True  True
e  True  True  True  True
f  True  True  True  True
h  True  True  True  True


In [217]:
if not True:
    print "true"
else :
    print "false"

false


In [222]:
filter(lambda x:re.search('.*null.*',x),dir(df3["one"]))

['isnull', 'notnull']

In [223]:
filter(lambda x:re.search('.*null.*',x),dir(pd))

['isnull', 'notnull']

In [251]:
df3["five"][3]=2
df3

C:\Users\17031172\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


one       two     three four  five
a -0.446368 -0.203396 -0.325042  bar     5
c  1.347684 -0.104033  0.319408  bar     5
e  0.234271 -0.811917  2.012418  bar     5
f -0.669014  0.835397 -0.187838  bar     2
h  1.403727  1.168214 -0.175217  bar     5

In [252]:
df3.replace({"five":{2:6}})

one       two     three four  five
a -0.446368 -0.203396 -0.325042  bar     5
c  1.347684 -0.104033  0.319408  bar     5
e  0.234271 -0.811917  2.012418  bar     5
f -0.669014  0.835397 -0.187838  bar     6
h  1.403727  1.168214 -0.175217  bar     5

In [243]:
np.isclose(-0.203396,df3["two"])

array([ True, False, False, False, False], dtype=bool)

In [254]:
s = pd.Series(np.random.randn(5), index=[0, 2, 4, 6, 7])
print s

0   -1.187612
2    0.938796
4    1.272922
6    0.473970
7   -1.516298
dtype: float64


In [259]:
 #(s > 0).reindex(list(range(8)))
s=(s > 0).reindex(range(8))
s

0    False
1      NaN
2     True
3      NaN
4     True
5      NaN
6     True
7    False
dtype: object

In [260]:
s.fillna(0)

0    False
1        0
2     True
3        0
4     True
5        0
6     True
7    False
dtype: object

In [261]:
df4 = pd.DataFrame({'X' : ['A', 'B', 'A', 'B'], 'Y' : [1, 4, 3, 2]})
df4

X  Y
0  A  1
1  B  4
2  A  3
3  B  2

In [271]:
df4.groupby(['X']).groups

{'A': [0L, 2L], 'B': [1L, 3L]}

In [264]:
df4.groupby(['X']).get_group('B')

X  Y
1  B  4
3  B  2

In [273]:
df4.groupby(['X'],as_index=False)

In [274]:
df4

X  Y
0  A  1
1  B  4
2  A  3
3  B  2

In [275]:
df4.unstack()

X  0    A
   1    B
   2    A
   3    B
Y  0    1
   1    4
   2    3
   3    2
dtype: object

In [277]:
temp=pd.DataFrame({'a':[1,3,3,4],
              'b':[1,3,3,5]})
print temp

   a  b
0  1  1
1  3  3
2  3  3
3  4  5


In [278]:
temp.drop_duplicates()

a  b
0  1  1
1  3  3
3  4  5

In [279]:
temp.replace(1,2)

a  b
0  2  2
1  3  3
2  3  3
3  4  5

In [280]:
pd.cut([11,15,18,20,25,26,27,24],[15,20,25])

[NaN, NaN, (15, 20], (15, 20], (20, 25], NaN, NaN, (20, 25]]
Categories (2, object): [(15, 20] < (20, 25]]

In [282]:
pd.cut([11,15,18,20,25,26,27,24],[15,20,25]).labels

C:\Users\17031172\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: 'labels' is deprecated. Use 'codes' instead
  if __name__ == '__main__':


array([-1, -1,  0,  0,  1, -1, -1,  1], dtype=int8)

In [283]:
pd.cut([11,15,18,20,25,26,27,24],[15,20,25]).levels

C:\Users\17031172\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: Accessing 'levels' is deprecated, use 'categories'
  if __name__ == '__main__':


Index([u'(15, 20]', u'(20, 25]'], dtype='object')

In [286]:
pd.value_counts(pd.cut([11,15,18,20,25,26,27,24],[15,20,25]),dropna=False)

NaN         4
(20, 25]    2
(15, 20]    2
dtype: int64

In [287]:
np.random.permutation(5)

array([1, 4, 2, 3, 0])

In [292]:
 isinstance("s",str)

True

In [291]:
a="s"
type(a)

str

In [293]:
type(0.32)

float

In [295]:
map(len,['adg','bdsa'])

[3, 4]

In [296]:
range(5)

[0, 1, 2, 3, 4]

In [299]:
divmod(10,3)

(3, 1)

In [300]:
coerce(10,3)

(10, 3)

In [301]:
round(0.2541245,2)

0.25

In [304]:
print range(100)[1:-1:2]

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97]


In [308]:
"".join(("a",'b','c'))

'abc'

In [310]:
dict(zip(list("abcdedf"),range(7)))

{'a': 0, 'b': 1, 'c': 2, 'd': 5, 'e': 4, 'f': 6}

In [311]:
conf = {'host':'127.0.0.1','db':'spam','user':'sa','passwd':'eggs'}
';'.join("%s=%s"%(k, v) for k, v in conf.iteritems())

'passwd=eggs;host=127.0.0.1;db=spam;user=sa'

In [312]:
import re

In [314]:
len(re.findall("s","sssssssssssss"))

13

In [321]:
df

A         B    C  D    F  E four
0  1  0.000000  0.0  3  foo  2  bar
1  0       NaN  1.0  3  foo  4  bar
2  1  0.698775  2.0  3  foo  3  bar
3  1  0.651240  3.0  3  foo  1  bar
4  1  0.525734  4.0  3  foo  3  bar

In [322]:
df.sort_values(by='E')

A         B    C  D    F  E four
3  1  0.651240  3.0  3  foo  1  bar
0  1  0.000000  0.0  3  foo  2  bar
2  1  0.698775  2.0  3  foo  3  bar
4  1  0.525734  4.0  3  foo  3  bar
1  0       NaN  1.0  3  foo  4  bar

In [323]:
pd.value_counts(df["A"])

1    4
0    1
Name: A, dtype: int64

In [324]:
df["A"].value_counts()

1    4
0    1
Name: A, dtype: int64

In [325]:
zip(df.columns,df.dtypes)

[('A', dtype('int64')),
 ('B', dtype('float64')),
 ('C', dtype('float32')),
 ('D', dtype('int32')),
 ('F', dtype('O')),
 ('E', category),
 ('four', dtype('O'))]

In [327]:
df.dtypes

A          int64
B        float64
C        float32
D          int32
F         object
E       category
four      object
dtype: object

In [328]:
df["A"].unique()

array([1, 0], dtype=int64)

In [330]:
df

A         B    C  D    F  E four
0  1  0.000000  0.0  3  foo  2  bar
1  0       NaN  1.0  3  foo  4  bar
2  1  0.698775  2.0  3  foo  3  bar
3  1  0.651240  3.0  3  foo  1  bar
4  1  0.525734  4.0  3  foo  3  bar

In [329]:
pd.melt(df,id_vars="A")

A variable     value
0   1        B         0
1   0        B       NaN
2   1        B  0.698775
3   1        B   0.65124
4   1        B  0.525734
5   1        C         0
6   0        C         1
7   1        C         2
8   1        C         3
9   1        C         4
10  1        D         3
11  0        D         3
12  1        D         3
13  1        D         3
14  1        D         3
15  1        F       foo
16  0        F       foo
17  1        F       foo
18  1        F       foo
19  1        F       foo
20  1        E         2
21  0        E         4
22  1        E         3
23  1        E         1
24  1        E         3
25  1     four       bar
26  0     four       bar
27  1     four       bar
28  1     four       bar
29  1     four       bar

In [332]:
df

A         B    C  D    F  E four
0  1  0.000000  0.0  3  foo  2  bar
1  0       NaN  1.0  3  foo  4  bar
2  1  0.698775  2.0  3  foo  3  bar
3  1  0.651240  3.0  3  foo  1  bar
4  1  0.525734  4.0  3  foo  3  bar

In [357]:
df["E"]=df["E"].astype(np.int32)
df[ (df["E"]>=3) & (pd.isnull(df["B"])==False) ]

A         B    C  D    F  E four
2  1  0.698775  2.0  3  foo  3  bar
4  1  0.525734  4.0  3  foo  3  bar

In [353]:
filter(lambda x:re.search(".*asty.*",x),dir(df["E"]))

['astype']

In [368]:
df.query("(E>1)&(C>2)")

A         B    C  D    F  E four
4  1  0.525734  4.0  3  foo  3  bar