#运行一个文件，比如建一个文件abc.py，文件内容为 print("abc")
import os
print os.getcwd()
#通过这种方式运行脚本
%run "abc.txt"

print "abd"

In [11]:
import numpy as np
a = np.arange(1,12,2).reshape(2,3)
print a

b =np.arange(0,11,2).reshape(2,3)

print b

print np.dstack((a, b))

oned = np.arange(2)

[[ 1  3  5]
 [ 7  9 11]]
[[ 0  2  4]
 [ 6  8 10]]
[[[ 1  0]
  [ 3  2]
  [ 5  4]]

 [[ 7  6]
  [ 9  8]
  [11 10]]]


In [13]:
a = np.arange(1,12,2)
print a

b =np.arange(0,11,2)

print b

print np.dstack((a, b))

[ 1  3  5  7  9 11]
[ 0  2  4  6  8 10]
[[[ 1  0]
  [ 3  2]
  [ 5  4]
  [ 7  6]
  [ 9  8]
  [11 10]]]


In [17]:
points = np.arange(-5, 5, 1) # 1000 equally spaced points
xs, ys = np.meshgrid(points, 2*points)
print xs,"\n",ys

[[-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]
 [-5 -4 -3 -2 -1  0  1  2  3  4]] 
[[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
 [ -8  -8  -8  -8  -8  -8  -8  -8  -8  -8]
 [ -6  -6  -6  -6  -6  -6  -6  -6  -6  -6]
 [ -4  -4  -4  -4  -4  -4  -4  -4  -4  -4]
 [ -2  -2  -2  -2  -2  -2  -2  -2  -2  -2]
 [  0   0   0   0   0   0   0   0   0   0]
 [  2   2   2   2   2   2   2   2   2   2]
 [  4   4   4   4   4   4   4   4   4   4]
 [  6   6   6   6   6   6   6   6   6   6]
 [  8   8   8   8   8   8   8   8   8   8]]


In [18]:
x = 3
print type(x) # Prints "<type 'int'>"
print x       # Prints "3"
print x + 1   # Addition; prints "4"
print x - 1   # Subtraction; prints "2"
print x * 2   # Multiplication; prints "6"
print x ** 2  # Exponentiation; prints "9"
x += 1
print x  # Prints "4"
x *= 2
print x  # Prints "8"
y = 2.5
print type(y) # Prints "<type 'float'>"
print y, y + 1, y * 2, y ** 2 # Prints "2.5 3.5 5.0 6.25"

<type 'int'>
3
4
2
6
9
4
8
<type 'float'>
2.5 3.5 5.0 6.25


In [ ]:
t = True
f = False
print type(t) # Prints "<type 'bool'>"
print t and f # Logical AND; prints "False"
print t or f  # Logical OR; prints "True"
print not t   # Logical NOT; prints "False"
print t != f  # Logical XOR; prints "True"  


hello = 'hello'   # String literals can use single quotes
world = "world"   # or double quotes; it does not matter.
print hello       # Prints "hello"
print len(hello)  # String length; prints "5"
hw = hello + ' ' + world  # String concatenation
print hw  # prints "hello world"
hw12 = '%s %s %d' % (hello, world, 12)  # sprintf style string formatting
print hw12  # prints "hello world 12"

In [21]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print np.reshape(v, (3, 1)) * w


[[ 4  5]
 [ 8 10]
 [12 15]]


In [22]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print y 

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [27]:
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
v.resize(3,1)

In [28]:
v*w

array([[ 4,  5],
       [ 8, 10],
       [12, 15]])

In [ ]:
from scipy.misc import imread, imsave, imresize

# Read an JPEG image into a numpy array
img = imread('assets/cat.jpg')
print img.dtype, img.shape  # Prints "uint8 (400, 248, 3)"

# We can tint the image by scaling each of the color channels
# by a different scalar constant. The image has shape (400, 248, 3);
# we multiply it by the array [1, 0.95, 0.9] of shape (3,);
# numpy broadcasting means that this leaves the red channel unchanged,
# and multiplies the green and blue channels by 0.95 and 0.9
# respectively.
img_tinted = img * [1, 0.95, 0.9]

# Resize the tinted image to be 300 by 300 pixels.
img_tinted = imresize(img_tinted, (300, 300))

# Write the tinted image back to disk
imsave('assets/cat_tinted.jpg', img_tinted)